#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    int2 ChunkCoord;
};

[[vk::image_format("r8ui")]]
RWTexture3D<uint> groupTexture : register(u0, space1);

[numthreads(CLEAR_GROUPS_THREADS_X, CLEAR_GROUPS_THREADS_Y, CLEAR_GROUPS_THREADS_Z)]
void main(uint3 id : SV_DispatchThreadID)
{
    int3 position = id + int3(ChunkCoord.x * (CHUNK_WIDTH / GROUP_SIZE), 0, ChunkCoord.y * (CHUNK_WIDTH / GROUP_SIZE));
    if (position.x >= GROUP_WIDTH || position.y >= GROUP_HEIGHT || position.z >= GROUP_WIDTH)
    {
        return;
    }
    groupTexture[position] = 0;
}
