#include "shader.hlsl"

[[vk::image_format("r8ui")]]
RWTexture3D<uint> macroTexture : register(u0, space1);

[numthreads(UPDATE_MACRO_BLOCKS_THREADS_X, UPDATE_MACRO_BLOCKS_THREADS_Y, UPDATE_MACRO_BLOCKS_THREADS_Z)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= WORLD_WIDTH * CHUNK_WIDTH / 8 || id.y >= CHUNK_HEIGHT / 8 || id.z >= WORLD_WIDTH * CHUNK_WIDTH / 8)
    {
        return;
    }
    macroTexture[id] = 0;
}