#include "shader.hlsl"

Texture3D<uint> blockTexture : register(t0, space0);
[[vk::image_format("r8ui")]]
RWTexture3D<uint> macroTexture : register(u0, space1);

[numthreads(8, 8, 8)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= WORLD_WIDTH * CHUNK_WIDTH || id.y >= CHUNK_HEIGHT || id.z >= WORLD_WIDTH * CHUNK_WIDTH)
    {
        return;
    }
    if (blockTexture[id] != kBlockAir)
    {
        macroTexture[id / 8] = 1;
    }
}
