#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    int2 Position;
};

Texture3D<uint> blockTexture : register(t0, space0);
[[vk::image_format("r8ui")]]
RWTexture3D<uint> groupTexture : register(u0, space1);

[numthreads(UPDATE_GROUPS_THREADS_X, UPDATE_GROUPS_THREADS_Y, UPDATE_GROUPS_THREADS_Z)]
void main(uint3 id : SV_DispatchThreadID)
{
    int3 position = id + int3(Position.x * CHUNK_WIDTH, 0, Position.y * CHUNK_WIDTH);
    if (position.x >= WORLD_WIDTH * CHUNK_WIDTH || position.y >= CHUNK_HEIGHT || position.z >= WORLD_WIDTH * CHUNK_WIDTH)
    {
        return;
    }
    if (blockTexture[position] != kBlockAir)
    {
        groupTexture[position / GROUP_SIZE] = 1;
    }
}
