#ifndef CONFIG_H
#define CONFIG_H

#define CHUNK_WIDTH 32
#define CHUNK_HEIGHT 32
#define WORLD_WIDTH 8
#define RAYTRACE_THREADS_X 8
#define RAYTRACE_THREADS_Y 8
#define WORLD_SET_BLOCKS_THREADS_X 128
#define WORLD_SET_CHUNKS_THREADS_X 32
#define CLEAR_BLOCKS_THREADS_X 8
#define CLEAR_BLOCKS_THREADS_Y 8

#endif