#ifndef CONFIG_H
#define CONFIG_H

#define CHUNK_WIDTH 32
#define CHUNK_HEIGHT 128
#define WORLD_WIDTH 10
#define RAY_TRACE_THREADS_X 16
#define RAY_TRACE_THREADS_Y 16
#define WORLD_SET_BLOCKS_THREADS_X 128
#define WORLD_SET_CHUNKS_THREADS_X 32
#define CLEAR_BLOCKS_THREADS_X 8
#define CLEAR_BLOCKS_THREADS_Y 8

#endif