#ifndef CONFIG_H
#define CONFIG_H

#define CHUNK_WIDTH 32
#define CHUNK_HEIGHT 128
#define WORLD_WIDTH 32

#ifdef __cplusplus
static_assert(CHUNK_WIDTH == 32, "Ensure it's divisible by 8 to ensure groups work properly");
#endif

#define CLEAR_BLOCKS_THREADS_X 8
#define CLEAR_BLOCKS_THREADS_Y 8
#define CLEAR_TEXTURE_THREADS_X 8
#define CLEAR_TEXTURE_THREADS_Y 8
#define RAYTRACE_THREADS_X 8
#define RAYTRACE_THREADS_Y 8
#define SAMPLE_TEXTURE_THREADS_X 8
#define SAMPLE_TEXTURE_THREADS_Y 8
#define SET_BLOCKS_THREADS_X 128
#define SET_CHUNKS_THREADS_X 32
#define UPDATE_MACRO_BLOCKS_THREADS_X 8
#define UPDATE_MACRO_BLOCKS_THREADS_Y 8
#define UPDATE_MACRO_BLOCKS_THREADS_Z 8

#endif