#ifndef THREADS_H
#define THREADS_H

#define RENDER_BLOCKS_THREADS_X 16
#define RENDER_BLOCKS_THREADS_Y 16
#define UPDATE_BLOCKS_THREADS_X 128
#define UPDATE_CHUNKS_THREADS_X 128
#define UPDATE_HEIGHTMAP_THREADS_X 128

#endif